// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 7.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'quizz';

  static const String assets_images_homebar_png = 'assets/images/homebar.png';
  static const String quizz$assets_images_homebar_png = 'packages/quizz/assets/images/homebar.png';

  static const String assets_images_i0_png = 'assets/images/i0.png';
  static const String quizz$assets_images_i0_png = 'packages/quizz/assets/images/i0.png';

  static const String assets_images_i1_png = 'assets/images/i1.png';
  static const String quizz$assets_images_i1_png = 'packages/quizz/assets/images/i1.png';

  static const String assets_images_i2_png = 'assets/images/i2.png';
  static const String quizz$assets_images_i2_png = 'packages/quizz/assets/images/i2.png';

  static const String assets_images_i3_png = 'assets/images/i3.png';
  static const String quizz$assets_images_i3_png = 'packages/quizz/assets/images/i3.png';

  static const String assets_images_p2_png = 'assets/images/p2.png';
  static const String quizz$assets_images_p2_png = 'packages/quizz/assets/images/p2.png';

  static const String assets_images_pa1_png = 'assets/images/pa1.png';
  static const String quizz$assets_images_pa1_png = 'packages/quizz/assets/images/pa1.png';
}
