// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 19.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'quizz';

  static const String assets_images_Cool_Kids_Sitting_png = 'assets/images/Cool_Kids_Sitting.png';
  static const String quizz$assets_images_Cool_Kids_Sitting_png = 'packages/quizz/assets/images/Cool_Kids_Sitting.png';

  static const String assets_images_fb_png = 'assets/images/fb.png';
  static const String quizz$assets_images_fb_png = 'packages/quizz/assets/images/fb.png';

  static const String assets_images_gg_png = 'assets/images/gg.png';
  static const String quizz$assets_images_gg_png = 'packages/quizz/assets/images/gg.png';

  static const String assets_images_handwriting_png = 'assets/images/handwriting.png';
  static const String quizz$assets_images_handwriting_png = 'packages/quizz/assets/images/handwriting.png';

  static const String assets_images_homebar_png = 'assets/images/homebar.png';
  static const String quizz$assets_images_homebar_png = 'packages/quizz/assets/images/homebar.png';

  static const String assets_images_i0_png = 'assets/images/i0.png';
  static const String quizz$assets_images_i0_png = 'packages/quizz/assets/images/i0.png';

  static const String assets_images_i1_png = 'assets/images/i1.png';
  static const String quizz$assets_images_i1_png = 'packages/quizz/assets/images/i1.png';

  static const String assets_images_i2_png = 'assets/images/i2.png';
  static const String quizz$assets_images_i2_png = 'packages/quizz/assets/images/i2.png';

  static const String assets_images_i3_png = 'assets/images/i3.png';
  static const String quizz$assets_images_i3_png = 'packages/quizz/assets/images/i3.png';

  static const String assets_images_iconAdd_png = 'assets/images/iconAdd.png';
  static const String quizz$assets_images_iconAdd_png = 'packages/quizz/assets/images/iconAdd.png';

  static const String assets_images_icons_add_50_png = 'assets/images/icons-add-50.png';
  static const String quizz$assets_images_icons_add_50_png = 'packages/quizz/assets/images/icons-add-50.png';

  static const String assets_images_icons1_add_50_png = 'assets/images/icons1-add-50.png';
  static const String quizz$assets_images_icons1_add_50_png = 'packages/quizz/assets/images/icons1-add-50.png';

  static const String assets_images_icons2_add_100_png = 'assets/images/icons2-add-100.png';
  static const String quizz$assets_images_icons2_add_100_png = 'packages/quizz/assets/images/icons2-add-100.png';

  static const String assets_images_icons8_add_50_png = 'assets/images/icons8-add-50.png';
  static const String quizz$assets_images_icons8_add_50_png = 'packages/quizz/assets/images/icons8-add-50.png';

  static const String assets_images_ig_png = 'assets/images/ig.png';
  static const String quizz$assets_images_ig_png = 'packages/quizz/assets/images/ig.png';

  static const String assets_images_p2_png = 'assets/images/p2.png';
  static const String quizz$assets_images_p2_png = 'packages/quizz/assets/images/p2.png';

  static const String assets_images_pa1_png = 'assets/images/pa1.png';
  static const String quizz$assets_images_pa1_png = 'packages/quizz/assets/images/pa1.png';

  static const String assets_images_trash_can_png = 'assets/images/trash-can.png';
  static const String quizz$assets_images_trash_can_png = 'packages/quizz/assets/images/trash-can.png';

  static const String assets_images_visibility1_png = 'assets/images/visibility1.png';
  static const String quizz$assets_images_visibility1_png = 'packages/quizz/assets/images/visibility1.png';
}
